base_config: "base.yml"

use_dpo: true
train_data_columns: ['chosen', 'rejected']
eval_data_columns: ['chosen', 'rejected']
base_output_directory: gs://rdyro/logs

# TFDS Pipeline ----------------------
dataset_type: tfds
dataset_path: 'gs://maxtext-dataset/dpo/anthropic_rlhf'
dataset_name: 'tfds:1.0.0'
eval_dataset_name: 'tfds:1.0.0'
eval_split: 'test'

#enable_checkpointing: true
gradient_clipping_threshold: 10.0
learning_rate: 5.0e-7
dpo_label_smoothing: 0.0
dpo_beta: 0.1

enable_goodput_recording: false
monitor_goodput: false
enable_checkpointing: false